
server:
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

config:
  styles:
    images:
      path: "\\src\\main\\resources\\img\\"
  securite:
    active: false

security:
  oauth2:
    client:
      client-id: fekoumbrek
      client-secret: fekoumbrek@123
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
