
server:
  port: 8083

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

config:
  styles:
    images:
      path: "http://localhost:8081/stylesImages"

security:
  oauth2:
    client:
      client-id: fekoumbrek
      client-secret: fekoumbrek@123
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
